services:
  - type: web
    name: creators-handbook
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
    autoDeploy: true
